import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Danal Design System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="wrap">
              <div id="header" className="header">
                          <Link href="/"  className="logo">
                          <Image src="/images/img_logo.png" 
                              alt="logo" 
                              width={250} height={45}/>
                          </Link>
                          <ul>
                              <li data-title="about">
                                <Link href="/about">About</Link>
                              </li>
                              <li data-title="foundation">
                                <Link href="/Foundation">Foundation</Link>
                              </li>
                              <li data-title="web">
                                <Link href="/web">Web</Link>
                              </li>
                              <li data-title="mobile">
                                <Link href="/mobile">Mobile</Link>
                              </li>
                              <li data-title="download">
                                <Link href="/download">Mownload</Link>
                              </li>
                          </ul>
              </div>
              <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
